### ISSUE TITLE
error when running setup.bat

### ISSUE THREAD

**Issue by MellowFishy** [0Xiaohei0/VoiceToJapanese#25]
Traceback (most recent call last):
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\MellowFishy\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\pipelines\__init__.py", line 45, in <module>
    from .audio_classification import AudioClassificationPipeline
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\pipelines\audio_classification.py", line 21, in <module>
    from .base import PIPELINE_INIT_ARGS, Pipeline
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\pipelines\base.py", line 36, in <module>
    from ..modelcard import ModelCard
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\modelcard.py", line 48, in <module>
    from .training_args import ParallelMode
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\training_args.py", line 60, in <module>
    import torch.distributed as dist
ModuleNotFoundError: No module named 'torch.distributed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\UI.py", line 6, in <module>
    import STTSLocal as STTS
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\STTSLocal.py", line 17, in <module>
    import translator
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\translator.py", line 2, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\VoiceToJapanese.v1.2.4-py\UI-v1.2.4-py\files\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
No module named 'torch.distributed'

**Comment by 0Xiaohei0** [comment]
Try installing torch manually, open a terminal in files folder
```
call .venv\Scripts\activate.bat
pip install torch
```
