### ISSUE TITLE
Some err idk ...💧

### ISSUE THREAD

**Issue by Fubuki-World0510** [0Xiaohei0/VoiceToJapanese#27]
```
Loading...
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\UI.py", line 6, in <module>
    import STTSLocal as STTS
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\STTSLocal.py", line 19, in <module>
    import whisper
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\whisper\__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\whisper\model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\whisper\transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\whisper\timing.py", line 7, in <module>
    import numba
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\Administrator\Downloads\UI-v1.2.5-py\files\.venv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
Press any key to continue . . .
```

**Comment by goenyan** [comment]
Try to run cmd in "files" folder, run ".venv\Scripts\activate.bat" command first, then "python ui.py"
