### ISSUE TITLE
Send User Input 1.2.6

### ISSUE THREAD

**Issue by pythontor** [0Xiaohei0/VoiceToJapanese#40]
I've got an issue in chatbot.py during the test. I wanted to ask my character ai bot in this by writing simple "Hello, how are you doing?" But intead ov vocal, or text output I've got an error. Here's what I got in response in console.

user: Hello, how are you doing?
Sending POST request to: http://127.0.0.1:3000
CHARACTER_AI_SERVER: TypeError: Cannot read properties of null (reading 'sendAndAwaitResponse')
CHARACTER_AI_SERVER: at C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\characterai_server.js:46:33
CHARACTER_AI_SERVER: at Layer.handle [as handle_request] (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\layer.js:95:5)
CHARACTER_AI_SERVER: at next (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\route.js:144:13)
CHARACTER_AI_SERVER: at Route.dispatch (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\route.js:114:3)
CHARACTER_AI_SERVER: at Layer.handle [as handle_request] (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\layer.js:95:5)
CHARACTER_AI_SERVER: at C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\index.js:284:15
CHARACTER_AI_SERVER: at Function.process_params (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\index.js:346:12)
CHARACTER_AI_SERVER: at next (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\index.js:280:10)
CHARACTER_AI_SERVER: at expressInit (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\middleware\init.js:40:5)
CHARACTER_AI_SERVER: at Layer.handle [as handle_request] (C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\node_modules\express\lib\router\layer.js:95:5)
response: <Response [500]>
Exception in thread Thread-20 (send_user_input):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\максим\Downloads\UI-v1.2.6-py\UI-v1.2.6-py\files\chatbot.py", line 143, in send_user_input
    response_json = json.loads(response.text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is there anyway you can help me?

**Comment by goenyan** [comment]
Response 500 usually caused by CAi server issue due to many users use it at the same time.
You can upgrade your CAi account to CAi+ to get more priority to use the API.
