### ISSUE TITLE
UI.EXE not launching. I have python 3.10.0

### ISSUE THREAD

**Issue by XB1TZ** [0Xiaohei0/VoiceToJapanese#46]
[CWAIFUUIUI.exe.txt](https://github.com/0Xiaohei0/VoiceToJapanese/files/13931911/CWAIFUUIUI.exe.txt)

**Comment by goenyan** [comment]
Why there is txt file?

**Comment by XB1TZ** [comment]
that's from cmd
Starting voicevox server...
Exception in thread Thread-1 (listen_to_mic):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "UI.py", line 1099, in listen_to_mic
  File "sounddevice.py", line 1800, in __init__
  File "sounddevice.py", line 800, in __init__
  File "sounddevice.py", line 2660, in _get_stream_parameters
  File "sounddevice.py", line 569, in query_devices
sounddevice.PortAudioError: Error querying device -1
Initializing tts model...
Initializing translator...
reading C:\Users\pc\AppData\Local\voicevox-engine\voicevox-engine\tmpa7akj6h1 ... 62
emitting double-array: 100% |###########################################|

done!
loading Audio devices:
loading config...
{'use_deepl': False, 'deepl_api_key': '', 'use_cloud_voice_vox': False, 'voice_vox_api_key': '', 'openai_api_key': '', 'youtube_video_id': '', 'twitch_access_token': '', 'twitch_channel_name': '', 'use_elevenlab': False, 'elevenlab_api_key': ''}
loading settings...
{'use_deepl': False, 'deepl_api_key': '', 'use_cloud_voice_vox': False, 'voice_vox_api_key': '', 'openai_api_key': '', 'youtube_video_id': '', 'twitch_access_token': '', 'twitch_channel_name': '', 'use_elevenlab': False, 'elevenlab_api_key': ''}
INFO:     127.0.0.1:11238 - "GET /speakers HTTP/1.1" 200 OK
[{'name': 'ノーマル', 'id': 2}, {'name': 'あまあま', 'id': 0}, {'name': 'ツンツン', 'id': 6}, {'name': 'セクシー', 'id': 4}, {'name': 'ささやき', 'id': 36}, {'name': 'ヒソヒソ', 'id': 37}]
Traceback (most recent call last):
  File "UI.py", line 1129, in <module>
  File "UI.py", line 1044, in __init__
  File "UI.py", line 805, in __init__
  File "UI.py", line 660, in __init__
  File "UI.py", line 403, in __init__
  File "UI.py", line 36, in __init__
  File "sounddevice.py", line 1421, in __init__
  File "sounddevice.py", line 817, in __init__
  File "sounddevice.py", line 2660, in _get_stream_parameters
  File "sounddevice.py", line 569, in query_devices
sounddevice.PortAudioError: Error querying device -1

**Comment by goenyan** [comment]
It can't load the list of audio devices.
Have you try to run it with Administrator?

**Comment by XB1TZ** [comment]
Yeah. The same happens.
